# Generated by Django 5.0.3 on 2024-03-30 06:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabulary', '0002_alter_dictionaryentry_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuizLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=100)),
            ],
            options={
                'db_table': 'DailyQuizLimit',
            },
        ),
        migrations.CreateModel(
            name='QuizCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial', models.IntegerField(default=0)),
                ('failure', models.IntegerField(default=0)),
                ('dictionary_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.dictionaryentry')),
            ],
            options={
                'db_table': 'QuizCount',
            },
        ),
        migrations.CreateModel(
            name='QuizSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=3)),
                ('interval', models.DurationField(default=datetime.timedelta(days=1))),
                ('next_date', models.DateField(default=datetime.date.today)),
                ('dictionary_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.dictionaryentry')),
            ],
            options={
                'db_table': 'QuizSchedule',
            },
        ),
    ]
