# Generated by Django 5.0.2 on 2024-02-17 02:32

import django.db.models.deletion
import vocabulary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(db_index=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'DictionaryEntry',
            },
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ja_name', models.CharField(max_length=50)),
                ('en_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PartOfSpeech',
            },
        ),
        migrations.CreateModel(
            name='EntryDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=512)),
                ('dictionary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_definitions', to='vocabulary.dictionaryentry')),
                ('part_of_speech', models.ForeignKey(default=vocabulary.models.get_default_part_of_speech, on_delete=django.db.models.deletion.SET_DEFAULT, to='vocabulary.partofspeech')),
            ],
            options={
                'db_table': 'EntryDefinition',
            },
        ),
    ]
