# Generated by Django 5.0.1 on 2024-01-10 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=512)),
                ('show_text', models.CharField(max_length=512)),
                ('meaning', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_of_speech', models.ForeignKey(default=10, on_delete=django.db.models.deletion.SET_DEFAULT, to='vocabulary.partofspeech')),
            ],
            options={
                'db_table': 'Vocabulary',
            },
        ),
    ]
