# Generated by Django 5.0.1 on 2024-01-21 04:11

import django.db.models.deletion
import vocabulary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_vocabulary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='part_of_speech',
            field=models.ForeignKey(default=vocabulary.models.get_default_part_of_speech, on_delete=django.db.models.deletion.SET_DEFAULT, to='vocabulary.partofspeech'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='search_text',
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
